from main import MyWindow, run_with_func

def test_styles(window: MyWindow):
    import time
    from layers import rainbow, lighten, black, invert
    # Additive draw mode
    window.change_draw_mode()
    window.on_increase_brush_size()
    window.on_increase_brush_size()
    window.on_paint(rainbow, 8, 8)
    time.sleep(1)
    window.on_paint(rainbow, 12, 12)
    time.sleep(1)
    window.on_decrease_brush_size()
    window.on_decrease_brush_size()
    window.on_paint(lighten, 9, 9)
    time.sleep(1)
    window.on_paint(lighten, 10, 10)
    time.sleep(1)
    window.on_paint(black, 11, 11)
    time.sleep(1)
    window.on_increase_brush_size()
    window.on_increase_brush_size()
    window.on_increase_brush_size()
    window.on_paint(invert, 11, 11)
    time.sleep(1)
    window.on_special()
    time.sleep(2)
    # Sequence draw mode
    window.change_draw_mode()
    # Brush gets reset to 2
    window.on_increase_brush_size()
    window.on_increase_brush_size()
    window.on_paint(rainbow, 20, 20)
    time.sleep(0.3)
    window.on_paint(rainbow, 18, 18)
    time.sleep(0.3)
    window.on_paint(rainbow, 16, 18)
    time.sleep(1)
    window.on_decrease_brush_size()
    window.on_decrease_brush_size()
    window.on_paint(black, 17, 15)
    time.sleep(1)
    window.on_paint(rainbow, 17, 13)
    time.sleep(1)
    window.on_increase_brush_size()
    window.on_increase_brush_size()
    window.on_paint(lighten, 16, 16)
    time.sleep(0.5)
    window.on_paint(lighten, 18, 18)
    time.sleep(1)
    window.on_paint(invert, 17, 17)
    time.sleep(1)
    window.on_special()
    time.sleep(1)
    window.on_special()
    time.sleep(1)
    window.on_special()
    time.sleep(2)

if __name__ == "__main__":
    run_with_func(test_styles)
